version: '3'

services:
  publications:
    image: ghcr.io/gh-network/ghostnetwork-publications:latest
    ports:
      - "5300:80"
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
