version: '3'

services:
  content:
    image: ghcr.io/ghosts-network/content:latest
    ports:
      - "5300:80"
    depends_on:
      - db
      - profiles
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development
      - PROFILES_ADDRESS=http://profiles

  profiles:
    image: ghcr.io/ghosts-network/profiles:latest
    ports:
      - "5400:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  profiles-grpc:
    image: ghcr.io/ghosts-network/grpcprofiles:latest
    ports:
      - "5600:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"

  gateway:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - content
      - profiles
      - profiles-grpc
    environment:
      - CONTENT_ADDRESS=http://content
      - PROFILES_ADDRESS=http://profiles
      - PROFILES_GRPC_ADDRESS=http://profiles-grpc
      - ASPNETCORE_ENVIRONMENT=Development
