name: Release GhostNetwork.EventHub.RabbitMq nuget

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: GhostNetwork.EventHub.RabbitMq
  PACKAGE_REGISTRY: https://api.nuget.org/v3/index.json

jobs:
  generate-nupkg:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Create package
        run: dotnet pack -o .
        working-directory: ./Libraries/GhostNetwork.EventBus.RabbitMq
      - name: Publish package
        run: dotnet nuget push $(ls | grep GhostNetwork.EventBus.RabbitMq.*.nupkg) --source $PACKAGE_REGISTRY --api-key ${{ secrets.NUGET_KEY }}
        working-directory: ./Libraries/GhostNetwork.EventBus.RabbitMq
