name: Release GhostNetwork.EventHub nuget

on:
  workflow_dispatch:

env:
  PACKAGE_REGISTRY: https://api.nuget.org/v3/index.json

jobs:
  generate-client:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Create package
        run: dotnet pack -o .
        working-directory: ./Libraries/GhostNetwork.EventBus
      - name: Publish package
        run: dotnet nuget push $(ls | grep GhostNetwork.EventBus.*.nupkg) --source $PACKAGE_REGISTRY --api-key ${{ secrets.NUGET_KEY }}
        working-directory: ./Libraries/GhostNetwork.EventBus
